### ISSUE TITLE
가상사이트 mid 인식문제에 관한 이슈

### ISSUE THREAD

**Issue by XisoDev** [largeden/multidomain#2]
github에쓰면 과연 보실까 해서 쪽지드렸었는데 ^^;

일단 제가 간단하게 살펴본결과

멀티도메인모듈에서 가상사이트의 mid를 저장하면 

triggerMultidomainInit 트리거 통과

-> 가상사이트의 site_srl같은걸 안줌

이때 모듈핸들러에서 module_info내부를 보면

ModuleHandler Object ( [module] => [act] => [mid] => home [document_srl] => 0 [module_srl] => 0 [module_info] => [error] => [httpStatusCode] => )

그러니 
if(Context::get('document_srl') || Context::get('mid') || Context::get('module') || Context::get('module_srl'))
{
	return;
}
를 통과하지못하니 triggerMultidomain 까지 진입을 못하죠.

예를들어 
main.xiso.co.kr 이 메인사이트이고
test.xiso.co.kr/home 을 멀티도메인모듈을 통해 지정했을경우에,

main.xiso.co.kr/home 을 불러오려 한다는겁니다. 하지만 main.xiso.co.kr 에는 home이라는 mid가 없으니 제쪽에서는 404에러가 떴었네요.

function triggerMultidomainInit(&$module_info)
	{
		$site_module_info->site_srl = 200;
		Context::set('site_module_info',$site_module_info);

모듈초기화 before 트리거앞부분에 이런식으로 site_srl을 걸어주면 정상적으로 찾아가긴 하나

getUrl 함수에서 도메인을 전부 기존 cafeXE에 등록된 도메인을 찾아가기때메 SSO를 사용하지않는경우 로그인이풀리며 원래 도메인으로 돌아가버리는 문제가 또 발생합니다.

나머지는 풀어서 해결해보시리라믿어용 ^^

**Comment by XisoDev** [comment]
지금 보내주신 쪽지 답장을 보니 가상사이트에 여러개의 도메인을 적용하는것에 대한 대응이 없는모듈이었군요.
시작mid를 지정할때 module_srl을 지정하길래 가능한줄알앗습니다. 지금은 triggerMultidomainInit초반에 site_module_info 를 저장된 module_srl을 불러와서 적용하는형태로 수정하여 사용하는중입니다.

**Comment by largeden** [comment]
@XisoDev  이곳에 이슈남겨주시면 바로 메일이 오기 때문에 편합니다. ^^

해당 기능을 추가하려면 아래의 함수에서 site_srl 존재여부로 추가 처리 해야합니다.

```php
	/**
	 * 멀티 도메인 상세 정보보기
	 * @param array $args
	 * @param array $columnList
	 * @return object
	 */
	function getMultidomain($args = array(), $columnList = array())
	{
		// cache를 불러옵니다.
		if($cache = $this->getMultidomainCache('object_getMultidomain', array($args->domain)))
		{
			return $cache;
		}
		$output = executeQuery('multidomain.getMultidomain', $args, $columnList);
		if(!$output->toBool()||!$output->data) return;
		// cache를 저장합니다.
		$this->setMultidomainCache('object_getMultidomain', array($args->domain), $output->data);
		return $output->data;
	}
```

해야하는 시나리오를 들려주시고, 멀티도메인 모듈에서 해소해야하는 부분이 있다면 고려해보겠습니다. :)

**Comment by XisoDev** [comment]
시나리오는 간단합니다.

가상사이트가 여러개의 도메인을 가질 수 있으면 되는거지요.

일단저는 모듈초기화 트리거에서

function triggerMultidomainInit(&$module_info)
	{
		// 멀티 도메인 수행 (가상사이트에 대응)
		$multidomain = $this->getMultidomainURL();
		if($multidomain->mid) Context::set('site_module_info',$multidomain);

이렇게 함수를 수정하고

getMultidomainUrl.xml 쿼리를 함께수정했습니다. (columns 노드에 modules.mid 부분을 modules.* 으로 수정했습니다. site_srl을 가져오기위해서요.)

그리고 링크마다 도메인이 바뀌는문제 (아마 이것때문에 기본url을 공란으로 비우도록 하신거같은데..가상사이트의 경우 그렇게해버리면 모든도메인이 기본사이트로 가버립니다.)는 Context 의 getUrl 함수에 $domain = $_SERVER['HTTP_HOST'] 를 넣어주어 해결했습니다.

**Comment by largeden** [comment]
@XisoDev 
$domain = $_SERVER['HTTP_HOST'] 이건 CSRF 문제 없을까요?

내용읽어보니 굳이 제가 해드릴 필욘 없을것 같네요. ^^

일단 이 이슈는 닫겠습니다.

나중에 필요한 부분이 있다면 다시 이야기해주세요.
