### ISSUE TITLE
글 등록이 안되요 T.T

### ISSUE THREAD

**Issue by mactopia** [largeden/multidomain#3]
가이드 대로 모듈 설치하고 
기본 도메인 설정 지우고, 도메인을 등록하고 문서 번호 지정한 이후

설정한 도메인으로 접속하면 위 문서 번호 지정한 문서로 바로 갑니다.

그래서 원래 사용하던 기존 도메인을 지우고, 추가 도메인만 등록해서 사용하면
기본 도메인에서 글등록이 안되는 현상이 나옵니다. 

해서 일단 해당 모듈을 지우고 기본 url 설정을 다시 등록하려하니 기본 url 이 등록이 안됩니다. 
(잘못된 요청이라고 나옵니다.)

**Comment by largeden** [comment]
제가 도메인만 3개여서 문서번호를 지정한 도메인으로 글을 적어보고,
또 문서번호 지정이 안된 도메인으로 접속해서도 글을 적어봤는데 이상이 없었습니다.

설정하고 있는 멀티 도메인 모듈 화면 캡쳐해서 올려주세요.

그리고 위 본문만 읽어보면 멀티 도메인에 추가 도메인만 설정되어있고 기본 도메인은 설정 안하신 걸로 읽혀집니다. 추가 도메인, 기본 도메인 모두 멀티 도메인 모듈내에 설정하고 계신지요?

![screen shot 2015-10-10 at 06 08 58](https://cloud.githubusercontent.com/assets/5575931/10405672/72b45da6-6f15-11e5-8d83-9bc852ff8c90.png)

**Comment by mactopia** [comment]
네. 기본 도메인 제거
기존 도메인 
새로 추가한 도메인 
모두 등록 이후 벌어진 일입니다.

일단 아쉽지만 실사용 사이트라 글쓰기가 필요해.. 일단 기존 설정대로 복구하고 멀티 도메인 모듈을 제거하였습니다. ^^: 하여 캡쳐는 현재 못올립니다. 감사합니다.

**Comment by largeden** [comment]
@mactopia 

다른 테스트 용 사이트가 있다면 그곳에서 테스트 해보세요.

제 생각에는 제대로 멀티 도메인 모듈에 도메인이 설정되어있음에도 CSRF를 통과 못시킨게 이유이고, 왜 통과를 못시켰는지는 @mactopia 님이 사용중인 사이트의 XE Core에 트리거를 이용하거나 도메인 관련 내용을 헨들링 하는 기능을 개발했거나 수정하여 사용중이시라면 그와 관련하여 문제가 난게 아닐까. 저는 이렇게 보고 있습니다.

또 사용 기회가 있다면 써보시고 문제 있으면 다시 이슈 남겨주시기 바랍니다.
